apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s.fullname" . }}
  labels:
    {{- include "k8s.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      # Add nodePort if using NodePort type
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort | default 30080 }}
      {{- end }}
  selector:
    {{- include "k8s.selectorLabels" . | nindent 4 }}
