apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: keycloak-backendconfig
  namespace: keycloak
spec:
  healthCheck:
    type: HTTP
    port: 80
    requestPath: /auth/realms/master/login
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3